Controllers/DoctorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GetCuredProject.Data;
using GetCuredProject.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using System.IO;

namespace GetCuredProject.Controllers
{
    [Authorize]
    public class DoctorController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IWebHostEnvironment _env;

        public DoctorController(ApplicationDbContext context, IWebHostEnvironment env)
        {
            _context = context;
            _env = env;
        }

        // GET: Doctor
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Doctor
                .Include(d => d.Hospital);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Doctor/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var doctorModel = await _context.Doctor
                .Include(d => d.Hospital)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (doctorModel == null)
            {
                return NotFound();
            }

            return View(doctorModel);
        }

        // GET: Doctor/Create
        public IActionResult Create()
        {
            ViewData["HospitalId"] = new SelectList(_context.HospitalOrClinic, "Id", "ClinicName");
            return View();
        }

        // POST: Doctor/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(DoctorModel doctorModel,IFormFile file)
        {
            if (ModelState.IsValid)
            {
                string fileName = string.Empty;
                if (file != null && file.Length > 0)
                {
                    fileName = file.FileName;
                    var path = Path.Combine(_env.WebRootPath, "uploads", file.FileName);
                    file.CopyTo(new FileStream(path, FileMode.Create));
                }
                doctorModel.FileName = fileName;
                _context.Add(doctorModel);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["HospitalId"] = new SelectList(_context.HospitalOrClinic, "Id", "ClinicName", doctorModel.HospitalId);
            return View(doctorModel);
        }

        // GET: Doctor/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var doctorModel = await _context.Doctor.FindAsync(id);
            if (doctorModel == null)
            {
                return NotFound();
            }
            ViewData["HospitalId"] = new SelectList(_context.HospitalOrClinic, "Id", "ClinicName", doctorModel.HospitalId);
            return View(doctorModel);
        }

        // POST: Doctor/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,DName,DPhone,DEmail,DGender,DQualification,DSpecialisation,DExperience,DRating,DFee,HospitalId,FromTime,ToTime")] DoctorModel doctorModel, IFormFile file)
        {
            if (id != doctorModel.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    string fileName = string.Empty;
                    if (file != null && file.Length > 0)
                    {
                        fileName = file.FileName;
                        var path = Path.Combine(_env.WebRootPath, "uploads", file.FileName);
                        file.CopyTo(new FileStream(path, FileMode.Create));
                    }
                    doctorModel.FileName = fileName;
                    _context.Update(doctorModel);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DoctorModelExists(doctorModel.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["HospitalId"] = new SelectList(_context.HospitalOrClinic, "Id", "ClinicName", doctorModel.HospitalId);
            return View(doctorModel);
        }

        // GET: Doctor/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var doctorModel = await _context.Doctor
                .Include(d => d.Hospital)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (doctorModel == null)
            {
                return NotFound();
            }

            return View(doctorModel);
        }

        // POST: Doctor/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var doctorModel = await _context.Doctor.FindAsync(id);
            _context.Doctor.Remove(doctorModel);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool DoctorModelExists(int id)
        {
            return _context.Doctor.Any(e => e.Id == id);
        }
    }
}

Controllers/PatientsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GetCuredProject.Data;
using GetCuredProject.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using System.IO;

namespace GetCuredProject.Controllers
{
    [Authorize]
    public class PatientsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IWebHostEnvironment _env;

        public PatientsController(ApplicationDbContext context, IWebHostEnvironment env)
        {
            _context = context;
            _env = env;
        }

        // GET: Patients
        public async Task<IActionResult> Index()
        {
            return View(await _context.Patients.ToListAsync());
        }

        // GET: Patients/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var patientsModel = await _context.Patients
                .FirstOrDefaultAsync(m => m.Id == id);
            if (patientsModel == null)
            {
                return NotFound();
            }

            return View(patientsModel);
        }

        // GET: Patients/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Patients/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,PName,PPhone,PEmail,PGender,PAge,PAddress,Weight,Vaccinated")] PatientsModel patientsModel, IFormFile file)
        {
            if (ModelState.IsValid)
            {
                string fileName = string.Empty;
                if (file != null && file.Length > 0)
                {
                    fileName = file.FileName;
                    var path = Path.Combine(_env.WebRootPath, "uploads", file.FileName);
                    file.CopyTo(new FileStream(path, FileMode.Create));
                }
                patientsModel.FileName = fileName;
                _context.Add(patientsModel);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(patientsModel);
        }

        // GET: Patients/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var patientsModel = await _context.Patients.FindAsync(id);
            if (patientsModel == null)
            {
                return NotFound();
            }
            return View(patientsModel);
        }

        // POST: Patients/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,PName,PPhone,PEmail,PGender,PAge,PAddress,Weight,Vaccinated")] PatientsModel patientsModel, IFormFile file)
        {
            if (id != patientsModel.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    string fileName = string.Empty;
                    if (file != null && file.Length > 0)
                    {
                        fileName = file.FileName;
                        var path = Path.Combine(_env.WebRootPath, "uploads", file.FileName);
                        file.CopyTo(new FileStream(path, FileMode.Create));
                    }
                    patientsModel.FileName = fileName;
                    _context.Update(patientsModel);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PatientsModelExists(patientsModel.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(patientsModel);
        }

        // GET: Patients/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var patientsModel = await _context.Patients
                .FirstOrDefaultAsync(m => m.Id == id);
            if (patientsModel == null)
            {
                return NotFound();
            }

            return View(patientsModel);
        }

        // POST: Patients/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var patientsModel = await _context.Patients.FindAsync(id);
            _context.Patients.Remove(patientsModel);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PatientsModelExists(int id)
        {
            return _context.Patients.Any(e => e.Id == id);
        }
    }
}

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GetCuredProject</title>
    <link rel="icon" href="/images/logo.jpg" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/AboutUs.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3" ">
            <div class="container">
                  <a class="navbar-brand" href="#">
    <img src="/images/logo.jpg" width="30" height="30" class="d-inline-block align-top" alt="logo">Getcured </a>
                @*<a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">GetCured</a>*@
               
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                         @if (SignInManager.IsSignedIn(User))
                        {
                            <li action="nav-item">
                                <a class="btn btn-outline-info"  style="margin-top : 10px ; margin-left : 10px; margin-bottom : 5px;" asp-area="" asp-controller="Patients" asp-action="Index"> PatientEntry </a>
                            </li>
                              <li action="nav-item">
                                <a class="btn btn-outline-primary"  style="margin-top : 10px ; margin-left : 10px; margin-bottom : 5px;" asp-area="" asp-controller="HospitalOrClinic" asp-action="Index"> HospitalOrClinic </a>
                            </li>
                              <li action="nav-item">
                                <a class="btn btn-outline-info"  style="margin-top : 10px ; margin-left : 10px; margin-bottom : 5px;" asp-area="" asp-controller="Doctor" asp-action="Index"> DoctorEntry </a>
                            </li>       
                              <li action="nav-item">
                                <a class="btn btn-outline-primary"  style="margin-top : 10px ; margin-left : 10px; margin-bottom : 5px;" asp-area="" asp-controller="Appointment" asp-action="Index"> Appointment </a>
                            </li>                      
                           @* <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Patients" asp-action="Index"><button type="button" class="btn btn-outline-info">PatientEntry</button></a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="HospitalOrClinic" asp-action="Index"><button type="button" class="btn btn-outline-primary">HospitalOrClinic</button></a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Doctor" asp-action="Index"><button type="button" class="btn btn-outline-info">DoctorsEntry</button></a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Appointment" asp-action="Index"><button type="button" class="btn btn-outline-primary">Appointments</button></a>
                            </li>*@
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - GetCured - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>